name: NexEngine
main: su.nexmedia.engine.NexEngine
loader: su.nexmedia.engine.NexEngineLoader
version: ${version}
api-version: 1.19
authors: [ NightExpress, Nailm ]
description: ${description}
load-before: [ ]
load-after: [ ]
load: STARTUP

dependencies:
  - name: Vault
    required: false
    bootstrap: false
  - name: Citizens
    required: false
    bootstrap: false
  - name: MythicMobs
    required: false
    bootstrap: false
