name: NexEngine
main: su.nexmedia.engine.NexEngine
version: ${version}
api-version: "1.19"
authors: [ NightExpress ]
contributors: [ Nailm ]
description: ${description}
dependencies:
  server:
    Vault:
      load: OMIT
      required: false
      join-classpath: true
    MythicMobs:
      load: OMIT
      required: false
      join-classpath: true